# Enable ZMK studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# nice_epaper
CONFIG_NICE_EPAPER_ON=y
CONFIG_NICE_OLED_ON=n
CONFIG_NICE_CUSTOM_ON=n

# Bongo cat + WPM + modifiers (from Cube Studio original config)
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=y
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_HOR=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_VER_ALIGN_LEFT=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_CUSTOM_X=2
CONFIG_NICE_OLED_WIDGET_MODIFIERS_CUSTOM_Y=110

# Sleep
CONFIG_ZMK_SLEEP=y

# BT
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Ext power
CONFIG_ZMK_EXT_POWER=y
