layout: {zmk_keyboard: corne_c}
layers:
  '0':
  - ESCAPE
  - Q
  - W
  - {t: '&e_td', h: '&'}
  - R
  - {t: T, h: '~'}
  - Y
  - U
  - I
  - O
  - {t: P, h: '%'}
  - BSPC
  - LSHFT
  - {t: '&a_td', h: '@'}
  - {t: S, h: $}
  - {t: D, h: '#'}
  - F
  - G
  - H
  - J
  - K
  - L
  - {t: '&apo_td', s: Sft+;}
  - RSHFT
  - LCTRL
  - Z
  - {t: X, h: '*'}
  - {t: '&c_td', h: '&macro_dotcom'}
  - V
  - B
  - N
  - M
  - ','
  - .
  - {t: '&slash_td', h: \}
  - DEL
  - LALT
  - '&mo1_gui'
  - SPACE
  - ENTER
  - '&l2_nav'
  - RCTRL
  '1':
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - F11
  - DEL
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '-'
  - {t: ▽, type: trans}
  - '?'
  - (
  - )
  - '|'
  - /
  - \
  - '`'
  - ^
  - Sft+'
  - ''''
  - _
  - '!'
  - LEFT ALT
  - {t: ▽, type: trans}
  - LSHFT
  - DELETE
  - RET
  - RCTRL
  '2':
  - INSERT
  - HOME
  - PG UP
  - UP ARROW
  - PAGE DOWN
  - '}'
  - KP 7
  - KP 8
  - KP 9
  - /
  - \
  - {t: ▽, type: trans}
  - DEL
  - END
  - LEFT ARROW
  - DOWN ARROW
  - RIGHT ARROW
  - '{'
  - KP 4
  - KP 5
  - KP 6
  - <
  - '>'
  - {t: ▽, type: trans}
  - PRINTSCREEN
  - LSHFT
  - LEFT CONTROL
  - '&key_repeat'
  - '['
  - ']'
  - KP 1
  - KP 2
  - KP 3
  - '-'
  - +
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - _
  - LOCKING NUM
  - KP 0
  - {t: ▽, type: trans}
  - KP DOT
  '3':
  - {t: ▽, type: trans}
  - OUT TOG
  - Ctl+LEFT
  - Ctl+RIGHT
  - Gui+LEFT
  - Gui+RIGHT
  - PAGE DOWN
  - DEL
  - UP
  - BSPC
  - PAGE UP
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - LGUI
  - PREV
  - PP
  - NEXT
  - ESCAPE
  - SCROLLLOCK
  - LEFT
  - DOWN
  - RIGHT
  - '`'
  - {t: ▽, type: trans}
  - LSHFT
  - BT PRV
  - BT NXT
  - VOL DN
  - VOL UP
  - MUTE
  - INS
  - HOME
  - INS
  - END
  - '~'
  - RSHFT
  - LCTRL
  - LEFT ALT
  - {t: ▽, type: trans}
  - ENTER
  - {t: ▽, type: trans}
  - '`'
  '4': [TAB, Q, W, E, R, T, '1', '2', '3', '4', '5', ESC, LSHFT, A, S, D, F, G, '6', '7', '8', '9', '0', RSHFT, LCTRL, Z, X, C, V, B, Y, H, N, J, '', RCTRL, LALT,
    SPACE, ENTER, ESC, CAPSLOCK, RALT]
  '5': [ESCAPE, A, Z, E, R, T, Y, U, I, O, P, BSPC, LSHFT, Q, S, D, F, G, H, J, K, L, M, RSHFT, LCTRL, W, X, C, V, B, N, ',', '''', ., /, DEL, LALT, '&mo1_gui', SPACE,
    ENTER, '&l2_nav', RCTRL]
combos:
- p: [0, 11]
  k: CLCK
  l: ['0']
- p: [30, 29]
  k: '&caps_word'
  l: ['0']
- p: [9, 10, 11]
  k: {t: '3', h: toggle}
  l: ['0', '1', '2', '3']
- p: [5, 17, 18, 6]
  k: {t: '4', h: toggle}
  l: ['0', '1', '2', '3', '4']
- p: [1, 2, 3, 4]
  k: {t: '5', h: toggle}
  l: ['0', '1', '2', '3', '4', '5']
- p: [11, 12, 0, 23]
  k: LOCKING NUM
  l: ['0']
- p: [3, 4, 14, 5]
  k: '&bootloader'
  l: ['0']
- p: [6, 7, 8, 21]
  k: '&bootloader'
  l: ['0']
- p: [3, 4]
  k: COPY
  l: ['0']
- p: [16, 15]
  k: PASTE
  l: ['0']
- p: [18, 6, 7]
  k: Alt+TAB
  l: ['0', '5']
- p: [6, 7]
  k: TAB
  l: ['0', '5']
